Repository vmware-tanzu/nsx-operator, pull requests merged in 2022-01, with the labels that each got.

#30 Add document for SecurityPolicy
  README.md
  docs/security-policy.md
Labels: cla-not-required

#29 Handle the SecurityPolicy CR update event
  build/yaml/samples/nsx_v1alpha1_securitypolicy.yaml
  pkg/nsx/services/firewall.go
  pkg/nsx/services/firewall_test.go
  pkg/nsx/services/store.go
Labels: cla-not-required

#31 GC support
  cmd/main.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/controllers/securitypolicy_controller.go
  pkg/nsx/cluster.go
  pkg/nsx/endpoint.go
  pkg/nsx/services/firewall.go
  pkg/nsx/services/firewall_test.go
  pkg/nsx/services/store.go
  pkg/nsx/transport.go
  pkg/nsx/util/utils.go
  pkg/util/types.go
Labels: cla-not-required

#34 Fix endpoint_test UT
  pkg/nsx/endpoint.go
  pkg/nsx/endpoint_test.go
Labels: cla-not-required

#37 Pass NSXOperatorConfig into service
  cmd/main.go
  pkg/nsx/services/firewall.go
  pkg/nsx/services/firewall_test.go
Labels: cla-not-required

#39 Remove log response body
  pkg/nsx/auth/jwt/vcclient.go
  pkg/nsx/util/utils.go
Labels: cla-not-required

#32 Run test in workflow
  .github/workflows/makefile.yml
Labels: cla-not-required

#35 Add nsx status checker for liveness probe
  cmd/main.go
  pkg/nsx/client.go
  pkg/nsx/cluster.go
Labels: cla-not-required

#40 Fix 2 issues
  pkg/nsx/endpoint.go
  pkg/nsx/services/store.go
Labels: bug

#42 Add thumbprint verify
  pkg/config/config.go
  pkg/controllers/securitypolicy_controller.go
  pkg/nsx/client.go
  pkg/nsx/cluster.go
  pkg/nsx/cluster_test.go
  pkg/nsx/config.go
  pkg/nsx/endpoint_test.go
  pkg/nsx/services/nsxapi_test.go
  pkg/nsx/transport.go
  pkg/nsx/transport_test.go
Labels: cla-not-required

#41 Add Sec Policy CR Ready status condition
  pkg/apis/v1alpha1/securitypolicy_types.go
  pkg/controllers/securitypolicy_controller.go
  pkg/controllers/securitypolicy_controller_test.go
Labels: enhancement, cla-not-required

#36 Add more logs for reconciling SecurityPolicy CR deletion
  pkg/controllers/securitypolicy_controller.go
Labels: cla-not-required

#47 Support CIDR in group for security policy
  pkg/nsx/services/firewall.go
Labels: cla-not-required

#46 Fix nsx requests not using token while token exists
  pkg/config/config.go
  pkg/nsx/auth/jwt/tesclient.go
  pkg/nsx/client.go
  pkg/nsx/cluster.go
Labels: cla-not-required

#38 Add MatchExpression support for SecurityPolicy
  pkg/nsx/services/firewall.go
  pkg/util/utils.go
Labels: cla-not-required
